### ISSUE TITLE
when using async and await the udpate command fails

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/hemera-sql-store#1]
When using async/await, it throws error as 1.

```
    public async update(data: ICount): Promise<ICount> {
        throw await this.hemera.act(
            {
                topic: NATS_HEMERA_DATBASE_MANAGER,
                cmd: 'update',
                collection: CounterRepository.tableName,
                query: {
                    id: data.id,
                },
                data: {
                    amount: data.amount,
                },
            },
        );
    }
    public async  addCount(amount) {
        return this.update({ id: 1, amount: amount });
    }
```

Test case
```

    it('addCount', async (done) => {
        try {
            await repo.addCount(1);
            done();
        } catch (err) {
            logger.error(err);
            done.fail();
        }
    });

```

Error
```
  ● Hemera-sql-store › addCount

    Failed

      at stackFormatter (../../node_modules/jest-jasmine2/build/expectation_result_factory.js:51:427)
      at Object.it (src/__tests__/hemera-repository.test.ts:130:18)
          at <anonymous>
```

**Comment by StarpTech** [comment]
Hi, 
what do you expect? You throw a value and the catch case is executed.

**Comment by veeramarni** [comment]
Haaa. I did not notice i have throw there. Let me check after correcting it.

**Comment by veeramarni** [comment]
my bad, thanks for your time though.
